### PR TITLE
Fix issue #44. Thanks to Klaus.

### PR DESCRIPTION
**Pull request by BSteelooper**

### CODE REVIEW

**Comment by BSteelooper** [comment]
@billcreswell I cannot commit directly to the pluck-cms/pluck repo. can you merge and republish a dev version?

**Comment by billcreswell** [comment]
Hmm. I thought I added all Dev rights to you.

**Comment by BSteelooper** [comment]
I get an not autorised error when pushing the commits.

**Comment by billcreswell** [comment]
Default Dev permission were set to read.

**Pull request merged**
